FROM ubuntu:latest
#or ubuntu:22.04 or ubuntu:20.04

RUN yes | unminimize

RUN apt install xxd -y

#RUN apt update -y 

#RUN apt upgrade -y

#RUN apt install python3 -y

RUN apt install curl -y

RUN apt install man-db -y

RUN apt install gcc -y

CMD ["/bin/bash"]